#!/usr/bin/env python3
"""FLUME verification VV-3 / VV-4 (issue #65, P2): compressible Couette flow and Becker's viscous shock.

Why: VV-1/VV-2 are linear waves in periodic boxes; they never touch a wall and never see a strong nonlinear viscous
flux. These two cases are exact steady solutions of the compressible Navier-Stokes equations (constant mu, k), so a
run started FROM the exact profile has that profile as its exact solution at every time: the departure at the end of
the run is the error of the scheme, walls and nonlinear fluxes included, with no relaxation transient to wait for and
no fit of a shock position.

- VV-3, `couette`: fixed isothermal wall (`T_w`) at y = 0, adiabatic wall moving at `U` along x at y = H; uniform p,
  `u = U y / H`, `T = T_w + mu U^2 / (k H) (y - y^2 / 2H)`. The wall ghosts are second order (the isothermal mirror
  `2 T_w - T` is exact only for a linear T), so the bound is on order 2, on u and T.
- VV-4, `becker`: Becker's (1922) shock, Pr = 3/4, constant mu, in the shock frame; supersonic inflow upstream,
  extrapolation downstream. The error is measured on u, normalised by the jump u1 - u2. The shock thickness scales
  with mu and shrinks with the Mach number: mu = 0.005 at M = 2 and 0.01 at M = 3 give both about 8 cells across the
  shock at N = 256 (at 4 cells WENO's nonlinear weights still act and the order is pre-asymptotic: +2.25 measured).

Usage:
    profiles.py make <out.ini> --case couette|becker --n N [--order 2|4] [--mach M] [--cfl C] [--time T]
    profiles.py oracle <work> [<work> ...] [--order-min P]
"""

from __future__ import annotations

import argparse
import configparser
import math
import sys
from pathlib import Path

import h5py
import numpy as np

GAMMA = 1.4
COUETTE = {"mu": 0.01, "prandtl": 0.75, "U": 1.0, "Tw": 1.0, "p": 1.0, "H": 1.0}
BECKER = {"mu": 0.005, "rho1": 1.0, "p1": 1.0 / GAMMA, "L": 0.25}

COMMON = """\
; FLUME verification {vv} (issue #65, P2): generated by verification/viscous/profiles.py, do not edit.
[IO]
output_basename        = profile
it_save                = 1000000
restart                = .false.
restart_basename       = profile-restart
restart_save           = 0
residuals_save         = 0
save_memory_status     = .false.
save_residual_fields   = .false.
save_auxiliary_fields  = .false.
save_curl_fields       = .false.
save_divergence_fields = .false.
save_gradient_fields   = .false.
save_laplacian_fields  = .false.

[grid]
ni     = {ni}
nj     = {nj}
nk     = 1
ngc    = 3
emin_x = {xmin!r}
emin_y = {ymin!r}
emin_z = 0.0
emax_x = {xmax!r}
emax_y = {ymax!r}
emax_z = 1.0
null_x = {null_x}
null_y = {null_y}
null_z = .true.

[amr]
max_level      = 2
ratio          = 4
iu_ref_levels  = 2
i_prune        = 0
j_prune        = 0
k_prune        = 0
l_prune        = -1
frequency      = 999999
iters          = 1
markers_number = 0

[field]
nv = 5

[runge_kutta]
scheme = runge-kutta-ssp-54

[weno]
scheme              = weno-u-5
ror_number          = 0
ror_threshold       = 0.9
ror_vars_number     = 0
enable_ror_stats    = .false.
ib_reduction_extent = 0
ib_reduced_order    = 2

[linear-algebra]
smoothing         = gauss-seidel
iterations_init   = 3
iterations_coarse = 10
iterations_fine   = 3
iterations        = 10
tolerance         = 1.e-20

[fdv]
fdv_scheme = fd
fdv_order  = 2

[solids]
number    = 0
n_eikonal = 0

[slices]
slices_number = 0

[physics]
physical_model = euler
gamma          = {gamma!r}
viscosity      = {mu!r}
prandtl        = {prandtl!r}

[numerics]
scheme_space             = weno
reconstruction_variables = characteristic
reflux                   = .true.
dissipative_order        = {order}

[time]
it_max   = -1
time_max = {time!r}
CFL      = {cfl!r}

[diagnostics]
conservation_history_save = 0

"""

COUETTE_TAIL = """\
[bc_x_min]
type = periodic
[bc_x_max]
type = periodic
[bc_y_min]
type             = wall-isothermal
wall_temperature = {Tw!r}
[bc_y_max]
type   = wall-noslip
wall_u = {U!r}
[bc_z_min]
type = extrapolation
[bc_z_max]
type = extrapolation

[initial_conditions]
type             = couette
amr_iterations   = 0
wall_y0          = 0.0
height           = {H!r}
wall_velocity    = {U!r}
wall_temperature = {Tw!r}

[initial_conditions_region_1]
r = 1.0
u = 0.0
v = 0.0
w = 0.0
p = {p!r}
"""

BECKER_TAIL = """\
[bc_x_min]
type = inflow
r    = {rho1!r}
u    = {u1!r}
v    = 0.0
w    = 0.0
p    = {p1!r}
[bc_x_max]
type = extrapolation
[bc_y_min]
type = extrapolation
[bc_y_max]
type = extrapolation
[bc_z_min]
type = extrapolation
[bc_z_max]
type = extrapolation

[initial_conditions]
type           = becker-shock
amr_iterations = 0
mach           = {mach!r}
shock_x0       = 0.0

[initial_conditions_region_1]
r = {rho1!r}
u = 0.0
v = 0.0
w = 0.0
p = {p1!r}
"""


def read_ini(path: Path) -> configparser.ConfigParser:
    """Read a FLUME INI file (`;` comments, no interpolation)."""
    ini = configparser.ConfigParser(inline_comment_prefixes=(";",), interpolation=None)
    ini.read(path)
    return ini


def make(args: argparse.Namespace) -> int:
    """Write one input: along y (Couette) or x (Becker), 4 blocks of n / 4 cells along the profile."""
    if args.n % 4 or args.n // 4 < 6:
        sys.exit("profiles.py: --n must be a multiple of 4 with n / 4 >= 6 (2 ngc)")
    if args.case == "couette":
        c = COUETTE
        # x is active and thin (4 blocks of 2 ngc = 6 cells, periodic): a null x would freeze rho u (CHASE semantics)
        text = COMMON.format(vv="VV-3", ni=6, nj=args.n // 4, xmin=0.0, xmax=1.0, ymin=0.0, ymax=c["H"],
                             null_x=".false.", null_y=".false.", gamma=GAMMA, mu=c["mu"], prandtl=c["prandtl"],
                             order=args.order, time=args.time, cfl=args.cfl)
        text += COUETTE_TAIL.format(**c)
    else:
        b = BECKER
        u1 = args.mach * math.sqrt(GAMMA * b["p1"] / b["rho1"])
        text = COMMON.format(vv="VV-4", ni=args.n // 4, nj=1, xmin=-b["L"], xmax=b["L"], ymin=0.0, ymax=1.0,
                             null_x=".false.", null_y=".true.", gamma=GAMMA, mu=args.mu or b["mu"], prandtl=0.75,
                             order=args.order, time=args.time, cfl=args.cfl)
        text += BECKER_TAIL.format(rho1=b["rho1"], u1=u1, p1=b["p1"], mach=args.mach)
    Path(args.out).write_text(text)
    return 0


def becker_u(x: np.ndarray, mach: float, mu: float) -> tuple[np.ndarray, float, float]:
    """Return Becker's exact velocity at x (shock at 0), u1 and u2 (the same implicit solution as the FLUME IC)."""
    u1 = mach * math.sqrt(GAMMA * BECKER["p1"] / BECKER["rho1"])
    u2 = u1 * ((GAMMA - 1.0) * mach**2 + 2.0) / ((GAMMA + 1.0) * mach**2)
    k = 3.0 * BECKER["rho1"] * u1 * (GAMMA + 1.0) / (8.0 * GAMMA * mu)

    def f(v: np.ndarray) -> np.ndarray:
        with np.errstate(divide="ignore"):
            return (u1 * np.log(u1 - v) - u2 * np.log(v - u2)) / (u1 - u2)

    rhs = k * x + f(np.array(0.5 * (u1 + u2)))
    lo, hi = np.full_like(x, u2), np.full_like(x, u1)
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        up = f(mid) > rhs
        lo, hi = np.where(up, mid, lo), np.where(up, hi, mid)
    return 0.5 * (lo + hi), u1, u2


def run_error(work: Path) -> tuple[int, float, float]:
    """Return (cells, error 1, error 2) of the last checkpoint: Couette RMS of u / U and T / T_w; Becker RMS and max of
    (u - u_exact) / (u1 - u2)."""
    ini = read_ini(work / "input.ini")
    ngc = int(ini["grid"]["ngc"])
    case = ini["initial_conditions"]["type"]
    files = sorted(work.glob("profile-*-proc*.h5"))
    if not files:
        sys.exit(f"profiles.py: no profile-*-proc*.h5 in {work}")
    last = max(int(f.name.split("-")[-2]) for f in files)
    e1, e2, emax, cells, dx = 0.0, 0.0, 0.0, 0, 0.0
    for path in (f for f in files if int(f.name.split("-")[-2]) == last):
        with h5py.File(path, "r") as h5:
            for blk in sorted({key.rsplit("-", 1)[0] for key in h5}):
                origin, dxyz = h5[f"{blk}-origin"][()][::-1], h5[f"{blk}-dxdydz"][()][::-1]

                def get(name: str, blk: str = blk, h5: h5py.File = h5) -> np.ndarray:
                    """Return the interior of one dataset of the block, (x, y), the null z dropped."""
                    return h5[f"{blk}-{name}"][()].transpose(2, 1, 0)[ngc:-ngc, ngc:-ngc, ngc:-ngc][:, :, 0]

                rho, ru, re = get("r"), get("ru"), get("rE")
                u = ru / rho
                p = (GAMMA - 1.0) * (re - 0.5 * rho * u**2)
                if case == "couette":
                    c = COUETTE
                    y = origin[1] + (np.arange(rho.shape[1]) + ngc + 0.5) * dxyz[1]
                    y = np.broadcast_to(y, rho.shape)
                    k = c["mu"] * GAMMA / (GAMMA - 1.0) / c["prandtl"]
                    temp = c["Tw"] + c["mu"] * c["U"] ** 2 / (k * c["H"]) * (y - y**2 / (2.0 * c["H"]))
                    e1 += float((((u - c["U"] * y / c["H"]) / c["U"]) ** 2).sum())
                    e2 += float((((p / rho - temp) / c["Tw"]) ** 2).sum())  # T = p / (rho R), R = 1
                    dx = dxyz[1]
                else:
                    x = origin[0] + (np.arange(rho.shape[0]) + ngc + 0.5) * dxyz[0]
                    x = np.broadcast_to(x[:, None], rho.shape)
                    ue, u1, u2 = becker_u(x, float(ini["initial_conditions"]["mach"]),
                                          float(ini["physics"]["viscosity"]))
                    err = np.abs(u - ue) / (u1 - u2)
                    e1 += float((err**2).sum())
                    emax = max(emax, float(err.max()))
                    dx = dxyz[0]
                cells += rho.size
    if case == "couette":
        return round(COUETTE["H"] / dx), math.sqrt(e1 / cells), math.sqrt(e2 / cells)
    return round(2.0 * BECKER["L"] / dx), math.sqrt(e1 / cells), emax


def oracle(args: argparse.Namespace) -> int:
    """Measure every run, print the errors and orders, assert the order of the finest pair on both errors."""
    case = read_ini(args.work[0] / "input.ini")["initial_conditions"]["type"]
    labels = ("RMS u/U", "RMS T/T_w") if case == "couette" else ("RMS du/(u1-u2)", "max du/(u1-u2)")
    results = sorted(run_error(w) for w in args.work)
    prev = None
    for n, a, b in results:
        line = f"N {n:4d}: {labels[0]} {a:.6e}  {labels[1]} {b:.6e}"
        if prev is not None:
            r = math.log(n / prev[0])
            line += f"  orders {math.log(prev[1] / a) / r:+.2f} {math.log(prev[2] / b) / r:+.2f}"
        print(line)
        prev = (n, a, b)
    status = 0
    if args.order_min is not None and len(results) > 1:
        (n0, a0, b0), (n1, a1, b1) = results[-2], results[-1]
        ps = [math.log(a0 / a1) / math.log(n1 / n0), math.log(b0 / b1) / math.log(n1 / n0)]
        status = int(min(ps) < args.order_min)
        print(f"finest-pair orders {ps[0]:+.2f} {ps[1]:+.2f} {'>=' if not status else '<'} {args.order_min}: "
              f"{'PASS' if not status else 'FAIL'}")
    return status


def main() -> int:
    """Dispatch the subcommand."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    pm = sub.add_parser("make", help="write one input")
    pm.add_argument("out")
    pm.add_argument("--case", choices=["couette", "becker"], required=True)
    pm.add_argument("--n", type=int, required=True, help="cells along the active direction")
    pm.add_argument("--order", type=int, choices=[2, 4], default=4)
    pm.add_argument("--mach", type=float, default=2.0)
    pm.add_argument("--mu", type=float, default=None, help="Becker viscosity (default 0.005; the thickness scales with it)")
    pm.add_argument("--cfl", type=float, default=0.2)
    pm.add_argument("--time", type=float, default=0.2)
    po = sub.add_parser("oracle", help="judge one or more runs")
    po.add_argument("work", type=Path, nargs="+")
    po.add_argument("--order-min", type=float, default=None)
    args = parser.parse_args()
    return make(args) if args.command == "make" else oracle(args)


if __name__ == "__main__":
    sys.exit(main())
