#!/usr/bin/env python3
"""FLUME verification VV-1 / VV-2 (issue #65, P2): viscous shear wave and viscous-thermal acoustic wave.

Why: the dissipative face fluxes must converge at their design order (2 or 4, `[numerics] dissipative_order`) and
carry the right coefficients. A small sine wave on a uniform gas at rest is a linear problem with an exact solution:
one Fourier mode of the linearised compressible Navier-Stokes equations, along the wave normal n,
```
d/dt (rho', u_n, T') = M (rho', u_n, T'),   d/dt u_t = -nu k^2 u_t
M = [[0,              -i k rho0,              0                 ],
     [-i k R T0/rho0, -4/3 mu k^2 / rho0,     -i k R            ],
     [0,              -i k p0 / (rho0 cv),    -kappa k^2 / (rho0 cv)]]
```
(`k` the wavenumber, `kappa` the conductivity, `p = rho R T`). The oracle integrates it exactly, `expm(M t)` by
eigendecomposition, from the Fourier coefficients of the initial condition, so it holds every mode the initial state
excites (the acoustic pair and the entropy mode), not just the Kirchhoff-Stokes rate:

- VV-1, `shear`: the transverse velocity `u_t = A sin(k n.x) exp(-nu k^2 t)`; the error is measured on u_t.
- VV-2, `acoustic`: the right-running acoustic wave, damped at the Kirchhoff-Stokes rate
  `alpha = k^2 / (2 rho0) (4/3 mu + (gamma - 1) kappa / cp)` to first order in `nu k / a`; the error is measured on
  rho'. The report also gives the measured amplitude decay against that rate (a cross-check of the oracle).

The waves are linear only to O(A^2): the shear wave's transverse velocity is not touched at that order, but an
acoustic wave steepens, and at A = 1e-4 its O(A^2) residue (1e-8) hides the discretisation error. The acoustic leg
therefore runs the twin with amplitude -A (`--sign -1`, work directory `<work>-neg`) and judges the odd part
`(f(+A) - f(-A)) / 2`, whose residue is O(A^3); with A = 1e-4 that residue (1e-12) still floored the finest
resolution, so the acoustic amplitude is A = 1e-5. The pointwise error is the RMS over the cells (point values: FLUME is a finite-difference scheme).

Usage:
    waves.py make <out.ini> --mode shear|acoustic --n N [--angle DEG] [--order 2|4] [--mu MU] [--kappa K] [--cfl C]
                  [--time T]
    waves.py oracle <work> [<work> ...] [--order-min P]     # one run per resolution, same case
"""

from __future__ import annotations

import argparse
import configparser
import math
import sys
from pathlib import Path

import h5py
import numpy as np

GAMMA = 1.4
RHO0, P0 = 1.0, 1.0
AMPLITUDE = 1.0e-4
AMPLITUDE_ACOUSTIC = 1.0e-5  # with the +/-A twin the residue is O(A^3) = 1e-15, round-off O(1e-16 / A) relative

TEMPLATE = """\
; FLUME verification {vv} (issue #65, P2): generated by verification/viscous/waves.py, do not edit.
[IO]
output_basename        = wave
it_save                = 1000000
restart                = .false.
restart_basename       = wave-restart
restart_save           = 0
residuals_save         = 0
save_memory_status     = .false.
save_residual_fields   = .false.
save_auxiliary_fields  = .false.
save_curl_fields       = .false.
save_divergence_fields = .false.
save_gradient_fields   = .false.
save_laplacian_fields  = .false.

[grid]
ni     = {ni}
nj     = {nj}
nk     = 1
ngc    = 3
emin_x = 0.0
emin_y = 0.0
emin_z = 0.0
emax_x = 1.0
emax_y = 1.0
emax_z = 1.0
null_x = {null_x}
null_y = {null_y}
null_z = .true.

[amr]
max_level      = 2
ratio          = 4
iu_ref_levels  = 2
i_prune        = 0
j_prune        = 0
k_prune        = 0
l_prune        = -1
frequency      = 999999
iters          = 1
markers_number = 0

[field]
nv = 5

[runge_kutta]
scheme = runge-kutta-ssp-54

[weno]
scheme              = weno-u-5
ror_number          = 0
ror_threshold       = 0.9
ror_vars_number     = 0
enable_ror_stats    = .false.
ib_reduction_extent = 0
ib_reduced_order    = 2

[linear-algebra]
smoothing         = gauss-seidel
iterations_init   = 3
iterations_coarse = 10
iterations_fine   = 3
iterations        = 10
tolerance         = 1.e-20

[fdv]
fdv_scheme = fd
fdv_order  = 2

[solids]
number    = 0
n_eikonal = 0

[slices]
slices_number = 0

[physics]
physical_model = euler
gamma          = {gamma!r}
viscosity      = {mu!r}
conductivity   = {kappa!r}

[numerics]
scheme_space             = weno
reconstruction_variables = characteristic
reflux                   = .true.
dissipative_order        = {order}

[bc_x_min]
type = periodic
[bc_x_max]
type = periodic
[bc_y_min]
type = periodic
[bc_y_max]
type = periodic
[bc_z_min]
type = extrapolation
[bc_z_max]
type = extrapolation

[initial_conditions]
type           = sine-wave
amr_iterations = 0
wave_mode      = {mode}
wave_angle     = {angle!r}
wave_amplitude = {amplitude!r}
wavelength     = {wavelength!r}

[initial_conditions_region_1]
r = {rho0!r}
u = 0.0
v = 0.0
w = 0.0
p = {p0!r}

[time]
it_max   = -1
time_max = {time!r}
CFL      = {cfl!r}

[diagnostics]
conservation_history_save = 0
"""


def read_ini(path: Path) -> configparser.ConfigParser:
    """Read a FLUME INI file (`;` comments, no interpolation)."""
    ini = configparser.ConfigParser(inline_comment_prefixes=(";",), interpolation=None)
    ini.read(path)
    return ini


def make(args: argparse.Namespace) -> int:
    """Write one input: the quadtree has 4 x 4 blocks of n / 4 cells per side. A wave along an axis needs the other
    in-plane axis only for its velocity: an acoustic wave runs on a one-cell-thick grid with that axis null, a shear
    wave keeps it active and thin (4 blocks of 2 ngc = 6 cells), because FLUME freezes the momentum normal to a null
    direction (CHASE semantics, `compute_flux_difference`), which would freeze the transverse velocity of the wave."""
    if args.n % 4 or args.n // 4 < 6:
        sys.exit("waves.py: --n must be a multiple of 4 with n / 4 >= 6 (2 ngc)")
    angle = float(args.angle)
    if angle % 45.0 != 0.0:
        sys.exit("waves.py: --angle must be a multiple of 45 degrees (periodic fit)")
    # the wave fits the unit periodic box: wavelength 1 along an axis, 1/sqrt(2) along a diagonal
    wavelength = 1.0 if angle % 90.0 == 0.0 else 1.0 / math.sqrt(2.0)
    ni = nj = args.n // 4
    null_x = null_y = ".false."
    thin, null_thin = (6, ".false.") if args.mode == "shear" else (1, ".true.")
    if angle % 180.0 == 0.0:
        nj, null_y = thin, null_thin
    elif angle % 180.0 == 90.0:
        ni, null_x = thin, null_thin
    text = TEMPLATE.format(vv="VV-1" if args.mode == "shear" else "VV-2", ni=ni, nj=nj, null_x=null_x, null_y=null_y,
                           gamma=GAMMA, mu=args.mu,
                           kappa=args.kappa, order=args.order, mode=args.mode, angle=angle,
                           amplitude=args.sign * (AMPLITUDE if args.mode == "shear" else AMPLITUDE_ACOUSTIC),
                           wavelength=wavelength, rho0=RHO0, p0=P0, time=args.time, cfl=args.cfl)
    Path(args.out).write_text(text)
    return 0


def linear_solution(ini: configparser.ConfigParser) -> tuple[str, float, np.ndarray, complex, float]:
    """Return (mode, k, n, exact complex coefficient of exp(i k n.x) of the measured field at time_max, cp)."""
    ph, ic = ini["physics"], ini["initial_conditions"]
    gamma, mu, kappa = float(ph["gamma"]), float(ph["viscosity"]), float(ph["conductivity"])
    r, cv = 1.0, 1.0 / (gamma - 1.0)  # gamma alone: R = 1 (issue #49, ND-2)
    cp = gamma * cv
    t = float(ini["time"]["time_max"])
    mode, a_amp = ic["wave_mode"], float(ic["wave_amplitude"])
    angle = math.radians(float(ic["wave_angle"]))
    k = 2.0 * math.pi / float(ic["wavelength"])
    n = np.array([math.cos(angle), math.sin(angle)])
    rho0 = float(ini["initial_conditions_region_1"]["r"])
    p0 = float(ini["initial_conditions_region_1"]["p"])
    t0 = p0 / (rho0 * r)
    if mode == "shear":
        # u_t = A sin(k s) = Re(-i A e^{iks})
        return mode, k, n, -1j * a_amp * math.exp(-mu / rho0 * k * k * t), cp
    # acoustic initial state (linearised): rho' = rho0 A sin, u_n = a A sin, p' = gamma p0 A sin
    a = math.sqrt(gamma * p0 / rho0)
    drho, du, dp = rho0 * a_amp, a * a_amp, gamma * p0 * a_amp
    dtemp = (dp / r - t0 * drho) / rho0  # T' from p' = R (rho0 T' + T0 rho')
    c0 = -1j * np.array([drho, du, dtemp])
    m = np.array([[0.0, -1j * k * rho0, 0.0],
                  [-1j * k * r * t0 / rho0, -4.0 / 3.0 * mu * k * k / rho0, -1j * k * r],
                  [0.0, -1j * k * p0 / (rho0 * cv), -kappa * k * k / (rho0 * cv)]], dtype=complex)
    lam, v = np.linalg.eig(m)
    ct = v @ (np.exp(lam * t) * np.linalg.solve(v, c0))
    return mode, k, n, complex(ct[0]), cp


def fields(work: Path) -> tuple[dict[str, tuple[np.ndarray, np.ndarray]], float]:
    """Return the measured field and the phase k n.x of every block of the last checkpoint, and the cell size."""
    ini = read_ini(work / "input.ini")
    ngc = int(ini["grid"]["ngc"])
    mode, k, n, _, _ = linear_solution(ini)
    rho0 = float(ini["initial_conditions_region_1"]["r"])
    files = sorted(work.glob("wave-*-proc*.h5"))
    if not files:
        sys.exit(f"waves.py: no wave-*-proc*.h5 in {work}")
    last = max(int(f.name.split("-")[-2]) for f in files)
    out, dx = {}, 0.0
    for path in (f for f in files if int(f.name.split("-")[-2]) == last):
        with h5py.File(path, "r") as h5:
            for blk in sorted({key.rsplit("-", 1)[0] for key in h5}):
                origin, dxyz = h5[f"{blk}-origin"][()][::-1], h5[f"{blk}-dxdydz"][()][::-1]

                def get(name: str, blk: str = blk, h5: h5py.File = h5) -> np.ndarray:
                    """Return the interior of one dataset of the block, (x, y), the null z dropped."""
                    return h5[f"{blk}-{name}"][()].transpose(2, 1, 0)[ngc:-ngc, ngc:-ngc, ngc:-ngc][:, :, 0]

                rho = get("r")
                xc = origin[0] + (np.arange(rho.shape[0]) + ngc + 0.5) * dxyz[0]
                yc = origin[1] + (np.arange(rho.shape[1]) + ngc + 0.5) * dxyz[1]
                xx, yy = np.meshgrid(xc, yc, indexing="ij")
                field = (-n[1] * get("ru") + n[0] * get("rv")) / rho if mode == "shear" else rho - rho0
                out[blk] = (k * (n[0] * xx + n[1] * yy), field)
                dx = min(dxyz[0], dxyz[1])  # a null direction spans the block
    return out, dx


def run_error(work: Path) -> tuple[int, float, float, float]:
    """Return (cells per side, RMS error, measured amplitude, exact amplitude) of the last checkpoint of one run.

    If the twin run `<work>-neg` (amplitude -A) exists, the measured field is the odd part `(f(+A) - f(-A)) / 2`: the
    even nonlinear terms cancel, so the residue is O(A^3) instead of O(A^2) (an acoustic wave steepens at O(A^2))."""
    _, _, _, coef, _ = linear_solution(read_ini(work / "input.ini"))
    pos, dx = fields(work)
    neg_work = work.parent / f"{work.name}-neg"
    neg = fields(neg_work)[0] if neg_work.is_dir() else None
    sq, cells, proj = 0.0, 0, 0.0 + 0.0j
    for blk, (s, field) in pos.items():
        if neg is not None:
            field = 0.5 * (field - neg[blk][1])
        exact = np.real(coef * np.exp(1j * s))
        sq += float(((field - exact) ** 2).sum())
        cells += field.size
        proj += complex((field * np.exp(-1j * s)).sum())
    return round(1.0 / dx), math.sqrt(sq / cells), 2.0 * abs(proj) / cells, abs(coef)


def oracle(args: argparse.Namespace) -> int:
    """Measure every run, print the errors and orders, assert the order of the finest pair."""
    ini = read_ini(args.work[0] / "input.ini")
    mode, k, _, _, cp = linear_solution(ini)
    ph = ini["physics"]
    mu, kappa = float(ph["viscosity"]), float(ph["conductivity"])
    gamma, t = float(ph["gamma"]), float(ini["time"]["time_max"])
    a0 = float(ini["initial_conditions"]["wave_amplitude"])
    rho0 = float(ini["initial_conditions_region_1"]["r"])
    if mode == "shear":
        print(f"exact decay rate nu k^2 = {mu / rho0 * k * k:.6e}")
    else:
        alpha = k * k / (2.0 * rho0) * (4.0 / 3.0 * mu + (gamma - 1.0) * kappa / cp)
        print(f"Kirchhoff-Stokes rate alpha = {alpha:.6e}")
    results = sorted(run_error(w) for w in args.work)
    prev = None
    for nn, err, measured, exact in results:
        rate = -math.log(measured / (a0 * (rho0 if mode == "acoustic" else 1.0))) / t
        line = f"N {nn:4d}: RMS error {err:.6e}  amplitude {measured:.10e} (exact {exact:.10e})  rate {rate:.6e}"
        if prev is not None:
            line += f"  order {math.log(prev[1] / err) / math.log(nn / prev[0]):+.2f}"
        print(line)
        prev = (nn, err)
    status = 0
    if args.order_min is not None and len(results) > 1:
        (n0, e0, _, _), (n1, e1, _, _) = results[-2], results[-1]
        p = math.log(e0 / e1) / math.log(n1 / n0)
        status = int(p < args.order_min)
        print(f"finest-pair order {p:+.2f} {'>=' if not status else '<'} {args.order_min}: "
              f"{'PASS' if not status else 'FAIL'}")
    return status


def main() -> int:
    """Dispatch the subcommand."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    pm = sub.add_parser("make", help="write one input")
    pm.add_argument("out")
    pm.add_argument("--mode", choices=["shear", "acoustic"], required=True)
    pm.add_argument("--n", type=int, required=True, help="cells per side")
    pm.add_argument("--angle", type=float, default=0.0, help="wave normal angle in the x-y plane, degrees")
    pm.add_argument("--order", type=int, choices=[2, 4], default=4)
    pm.add_argument("--mu", type=float, default=0.01)
    pm.add_argument("--kappa", type=float, default=0.0)
    pm.add_argument("--cfl", type=float, default=0.2)
    pm.add_argument("--time", type=float, default=0.5)
    pm.add_argument("--sign", type=int, choices=[1, -1], default=1, help="sign of the amplitude (the -A twin run)")
    po = sub.add_parser("oracle", help="judge one or more runs")
    po.add_argument("work", type=Path, nargs="+")
    po.add_argument("--order-min", type=float, default=None)
    args = parser.parse_args()
    return make(args) if args.command == "make" else oracle(args)


if __name__ == "__main__":
    sys.exit(main())
