#!/usr/bin/env python3
"""FLUME verification VV-1 / VV-2 (issue #65, P2): viscous shear wave and viscous-thermal acoustic wave.

Why: the dissipative face fluxes must converge at their design order (2 or 4, `[numerics] dissipative_order`) and
carry the right coefficients. A small sine wave on a uniform gas at rest is a linear problem with an exact solution:
one Fourier mode of the linearised compressible Navier-Stokes equations, along the wave normal n,
```
d/dt (rho', u_n, T') = M (rho', u_n, T'),   d/dt u_t = -nu k^2 u_t
M = [[0,              -i k rho0,              0                 ],
     [-i k R T0/rho0, -4/3 mu k^2 / rho0,     -i k R            ],
     [0,              -i k p0 / (rho0 cv),    -kappa k^2 / (rho0 cv)]]
```
(`k` the wavenumber, `kappa` the conductivity, `p = rho R T`). The oracle integrates it exactly, `expm(M t)` by
eigendecomposition, from the Fourier coefficients of the initial condition, so it holds every mode the initial state
excites (the acoustic pair and the entropy mode), not just the Kirchhoff-Stokes rate:

- VV-1, `shear`: the transverse velocity `u_t = A sin(k n.x) exp(-nu k^2 t)`; the error is measured on u_t.
- VV-2, `acoustic`: the right-running acoustic wave, damped at the Kirchhoff-Stokes rate
  `alpha = k^2 / (2 rho0) (4/3 mu + (gamma - 1) kappa / cp)` to first order in `nu k / a`; the error is measured on
  rho'. The report also gives the measured amplitude decay against that rate (a cross-check of the oracle).

The waves are linear only to O(A^2): the shear wave's transverse velocity is not touched at that order, but an
acoustic wave steepens, and at A = 1e-4 its O(A^2) residue (1e-8) hides the discretisation error. The acoustic leg
therefore runs the twin with amplitude -A (`--sign -1`, work directory `<work>-neg`) and judges the odd part
`(f(+A) - f(-A)) / 2`, whose residue is O(A^3); with A = 1e-4 that residue (1e-12) still floored the finest
resolution, so the acoustic amplitude is A = 1e-5. The pointwise error is the RMS over the cells (point values: FLUME is a finite-difference scheme).

P4 (VV-7, VV-8): `--refine` adds one 2:1 level over the blocks whose centroid lies in a box (`mhd/amr_box.py`, quadtree
`--ratio 4` or octree `--ratio 8`), so the wave crosses coarse-fine seams; `--reflux false` is the negative control of
the conservation leg. On a composite grid the RMS and the amplitude are weighted by the cell area (on a uniform grid
the weights are equal and the measure is the plain RMS).

Usage:
    waves.py make <out.ini> --mode shear|acoustic --n N [--angle DEG] [--order 2|4] [--mu MU] [--kappa K] [--cfl C]
                  [--time T] [--refine XMIN YMIN XMAX YMAX [--ratio 4|8]] [--reflux true|false]
    waves.py oracle <work> [<work> ...] [--order-min P]     # one run per resolution, same case
"""

from __future__ import annotations

import argparse
import configparser
import math
import sys
from pathlib import Path

import h5py
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "mhd"))
from amr_box import refine_box  # noqa: E402

GAMMA = 1.4
RHO0, P0 = 1.0, 1.0
AMPLITUDE = 1.0e-4
AMPLITUDE_ACOUSTIC = 1.0e-5  # with the +/-A twin the residue is O(A^3) = 1e-15, round-off O(1e-16 / A) relative
AMPLITUDE_MAGNETIC = 1.0e-5  # the wave's magnetic pressure drives an O(A^2) flow that advects it at O(A^3), odd in A
                             # (no twin cancels it): relative A^2 = 1e-10 here, 1e-8 at 1e-4, a fifth of the finest
                             # diagonal error; with no background B there is no round-off cost (B is the small number)

TEMPLATE = """\
; FLUME verification {vv} (issue #65, P2): generated by verification/viscous/waves.py, do not edit.
[IO]
output_basename        = wave
it_save                = 1000000
restart                = .false.
restart_basename       = wave-restart
restart_save           = 0
residuals_save         = 0
save_memory_status     = .false.
save_residual_fields   = .false.
save_auxiliary_fields  = .false.
save_curl_fields       = .false.
save_divergence_fields = .false.
save_gradient_fields   = .false.
save_laplacian_fields  = .false.

[grid]
ni     = {ni}
nj     = {nj}
nk     = 1
ngc    = 3
emin_x = 0.0
emin_y = 0.0
emin_z = 0.0
emax_x = 1.0
emax_y = 1.0
emax_z = 1.0
null_x = {null_x}
null_y = {null_y}
null_z = .true.

[amr]
max_level      = 2
ratio          = 4
iu_ref_levels  = 2
i_prune        = 0
j_prune        = 0
k_prune        = 0
l_prune        = -1
frequency      = 999999
iters          = 1
markers_number = 0

[field]
nv = {nv}

[runge_kutta]
scheme = runge-kutta-ssp-54

[weno]
scheme              = weno-u-5
ror_number          = 0
ror_threshold       = 0.9
ror_vars_number     = 0
enable_ror_stats    = .false.
ib_reduction_extent = 0
ib_reduced_order    = 2

[linear-algebra]
smoothing         = gauss-seidel
iterations_init   = 3
iterations_coarse = 10
iterations_fine   = 3
iterations        = 10
tolerance         = 1.e-20

[fdv]
fdv_scheme = fd
fdv_order  = 2

[solids]
number    = 0
n_eikonal = 0

[slices]
slices_number = 0

[physics]
physical_model = {model}
gamma          = {gamma!r}
viscosity      = {mu!r}
conductivity   = {kappa!r}
{resistivity}
[numerics]
scheme_space             = weno
reconstruction_variables = characteristic
reflux                   = .true.
dissipative_order        = {order}

[bc_x_min]
type = periodic
[bc_x_max]
type = periodic
[bc_y_min]
type = periodic
[bc_y_max]
type = periodic
[bc_z_min]
type = extrapolation
[bc_z_max]
type = extrapolation

[initial_conditions]
type           = sine-wave
amr_iterations = 0
wave_mode      = {mode}
wave_angle     = {angle!r}
wave_amplitude = {amplitude!r}
wavelength     = {wavelength!r}

[initial_conditions_region_1]
r = {rho0!r}
u = 0.0
v = 0.0
w = 0.0
p = {p0!r}
{field_keys}
[time]
it_max   = -1
time_max = {time!r}
CFL      = {cfl!r}

[diagnostics]
conservation_history_save = 1
{mhd_section}"""

MHD_SECTION = """
[mhd]
divergence_control = {control}
divb_tol           = 0.0
divb_error         = .false.
rho_floor          = 0.0
p_floor            = 0.0
glm_ch             = 3.0
glm_alpha          = 0.0
glm_damping_length = 1.0
glm_ch_check       = error
"""


def read_ini(path: Path) -> configparser.ConfigParser:
    """Read a FLUME INI file (`;` comments, no interpolation)."""
    ini = configparser.ConfigParser(inline_comment_prefixes=(";",), interpolation=None)
    ini.read(path)
    return ini


def make(args: argparse.Namespace) -> int:
    """Write one input: the quadtree has 4 x 4 blocks of n / 4 cells per side. A wave along an axis needs the other
    in-plane axis only for its velocity: an acoustic wave runs on a one-cell-thick grid with that axis null, a shear
    wave keeps it active and thin (4 blocks of 2 ngc = 6 cells), because FLUME freezes the momentum normal to a null
    direction (CHASE semantics, `compute_flux_difference`), which would freeze the transverse velocity of the wave."""
    if args.n % 4 or args.n // 4 < 6:
        sys.exit("waves.py: --n must be a multiple of 4 with n / 4 >= 6 (2 ngc)")
    angle = float(args.angle)
    if angle % 45.0 != 0.0:
        sys.exit("waves.py: --angle must be a multiple of 45 degrees (periodic fit)")
    # the wave fits the unit periodic box: wavelength 1 along an axis, 1/sqrt(2) along a diagonal
    wavelength = 1.0 if angle % 90.0 == 0.0 else 1.0 / math.sqrt(2.0)
    ni = nj = args.n // 4
    null_x = null_y = ".false."
    thin, null_thin = (1, ".true.") if args.mode == "acoustic" else (6, ".false.")
    mhd = args.model != "euler"
    if args.mode == "magnetic" and not mhd:
        sys.exit("waves.py: --mode magnetic needs an MHD --model")
    control = args.model.split("-")[1] if mhd else ""
    b0 = args.b0 * np.array([math.cos(math.radians(angle)), math.sin(math.radians(angle))])
    if angle % 180.0 == 0.0:
        nj, null_y = thin, null_thin
    elif angle % 180.0 == 90.0:
        ni, null_x = thin, null_thin
    vv = {"shear": "VV-1", "acoustic": "VV-2", "magnetic": "VV-5"}[args.mode]
    text = TEMPLATE.format(vv=vv, ni=ni, nj=nj, null_x=null_x, null_y=null_y, nv=(9 if control in ("glm", "eglm") else 8)
                           if mhd else 5, model="mhd-ideal" if mhd else "euler", gamma=GAMMA, mu=args.mu,
                           kappa=args.kappa, resistivity=f"resistivity    = {args.eta!r}\n" if mhd else "",
                           order=args.order, mode=args.mode, angle=angle,
                           amplitude=args.amplitude if args.amplitude is not None else
                           args.sign * {"shear": AMPLITUDE, "acoustic": AMPLITUDE_ACOUSTIC,
                                        "magnetic": AMPLITUDE_MAGNETIC}[args.mode],
                           wavelength=wavelength, rho0=RHO0, p0=P0,
                           field_keys=f"bx = {float(b0[0])!r}\nby = {float(b0[1])!r}\nbz = 0.0\n" if mhd else "",
                           time=args.time, cfl=args.cfl,
                           mhd_section=MHD_SECTION.format(control=control) if mhd else "")
    if args.refine is not None or args.reflux != "true" or args.bc_x != "periodic":
        ini = configparser.ConfigParser(inline_comment_prefixes=(";",), interpolation=None)
        ini.optionxform = str  # FLUME keys are case-sensitive (e.g. [time] CFL)
        ini.read_string(text)
        ini["numerics"]["reflux"] = f".{args.reflux}."
        for face in ("bc_x_min", "bc_x_max"):
            ini[face]["type"] = args.bc_x
        if args.refine is not None:
            refine_box(ini, args.refine, ratio=args.ratio)
        with Path(args.out).open("w") as out:
            out.write(text.splitlines()[0] + "\n")
            ini.write(out)
    else:
        Path(args.out).write_text(text)
    return 0


def linear_solution(ini: configparser.ConfigParser) -> tuple[str, float, np.ndarray, complex, float]:
    """Return (mode, k, n, exact complex coefficient of exp(i k n.x) of the measured field at time_max, cp)."""
    ph, ic = ini["physics"], ini["initial_conditions"]
    gamma, mu, kappa = float(ph["gamma"]), float(ph["viscosity"]), float(ph["conductivity"])
    r, cv = 1.0, 1.0 / (gamma - 1.0)  # gamma alone: R = 1 (issue #49, ND-2)
    cp = gamma * cv
    t = float(ini["time"]["time_max"])
    mode, a_amp = ic["wave_mode"], float(ic["wave_amplitude"])
    angle = math.radians(float(ic["wave_angle"]))
    k = 2.0 * math.pi / float(ic["wavelength"])
    n = np.array([math.cos(angle), math.sin(angle)])
    rho0 = float(ini["initial_conditions_region_1"]["r"])
    p0 = float(ini["initial_conditions_region_1"]["p"])
    t0 = p0 / (rho0 * r)
    if mode in ("shear", "magnetic"):
        # transverse velocity and field, (v_t, b_t), coupled by the normal field B_n (Alfven), damped by nu and eta:
        # d/dt (v, b) = [[-nu k^2, i k B_n / rho], [i k B_n, -eta k^2]] (v, b); A sin(k s) = Re(-i A e^{iks})
        eta = float(ph.get("resistivity", "0.0"))
        reg = ini["initial_conditions_region_1"]
        bn = float(reg.get("bx", "0.0")) * n[0] + float(reg.get("by", "0.0")) * n[1]
        m = np.array([[-mu / rho0 * k * k, 1j * k * bn / rho0], [1j * k * bn, -eta * k * k]], dtype=complex)
        c0 = -1j * a_amp * (np.array([1.0, 0.0]) if mode == "shear" else np.array([0.0, 1.0]))
        if bn == 0.0 and eta == 0.0 and mode == "shear":  # the P2 case: no eigen-solve, the closed form
            return mode, k, n, -1j * a_amp * math.exp(-mu / rho0 * k * k * t), cp
        lam, v = np.linalg.eig(m)
        ct = v @ (np.exp(lam * t) * np.linalg.solve(v, c0))
        return mode, k, n, complex(ct[0] if mode == "shear" else ct[1]), cp
    # acoustic initial state (linearised): rho' = rho0 A sin, u_n = a A sin, p' = gamma p0 A sin
    a = math.sqrt(gamma * p0 / rho0)
    drho, du, dp = rho0 * a_amp, a * a_amp, gamma * p0 * a_amp
    dtemp = (dp / r - t0 * drho) / rho0  # T' from p' = R (rho0 T' + T0 rho')
    c0 = -1j * np.array([drho, du, dtemp])
    m = np.array([[0.0, -1j * k * rho0, 0.0],
                  [-1j * k * r * t0 / rho0, -4.0 / 3.0 * mu * k * k / rho0, -1j * k * r],
                  [0.0, -1j * k * p0 / (rho0 * cv), -kappa * k * k / (rho0 * cv)]], dtype=complex)
    lam, v = np.linalg.eig(m)
    ct = v @ (np.exp(lam * t) * np.linalg.solve(v, c0))
    return mode, k, n, complex(ct[0]), cp


def fields(work: Path) -> tuple[dict[str, tuple[np.ndarray, np.ndarray, float]], float]:
    """Return the phase k n.x, the measured field and the cell area of every block of the last checkpoint, and the
    smallest cell size."""
    ini = read_ini(work / "input.ini")
    ngc = int(ini["grid"]["ngc"])
    mode, k, n, _, _ = linear_solution(ini)
    rho0 = float(ini["initial_conditions_region_1"]["r"])
    files = sorted(work.glob("wave-*-proc*.h5"))
    if not files:
        sys.exit(f"waves.py: no wave-*-proc*.h5 in {work}")
    last = max(int(f.name.split("-")[-2]) for f in files)
    out, dx = {}, 0.0
    for path in (f for f in files if int(f.name.split("-")[-2]) == last):
        with h5py.File(path, "r") as h5:
            for blk in sorted({key.rsplit("-", 1)[0] for key in h5}):
                origin, dxyz = h5[f"{blk}-origin"][()][::-1], h5[f"{blk}-dxdydz"][()][::-1]

                def get(name: str, blk: str = blk, h5: h5py.File = h5) -> np.ndarray:
                    """Return the interior of one dataset of the block, (x, y), the null z dropped."""
                    return h5[f"{blk}-{name}"][()].transpose(2, 1, 0)[ngc:-ngc, ngc:-ngc, ngc:-ngc][:, :, 0]

                rho = get("r")
                xc = origin[0] + (np.arange(rho.shape[0]) + ngc + 0.5) * dxyz[0]
                yc = origin[1] + (np.arange(rho.shape[1]) + ngc + 0.5) * dxyz[1]
                xx, yy = np.meshgrid(xc, yc, indexing="ij")
                if mode == "shear":
                    field = (-n[1] * get("ru") + n[0] * get("rv")) / rho
                elif mode == "magnetic":
                    field = -n[1] * get("bx") + n[0] * get("by")
                else:
                    field = rho - rho0
                out[blk] = (k * (n[0] * xx + n[1] * yy), field, float(dxyz[0] * dxyz[1]))
                h = min(dxyz[0], dxyz[1])  # a null direction spans the block
                dx = h if dx == 0.0 else min(dx, h)
    return out, dx


def run_error(work: Path) -> tuple[int, float, float, float]:
    """Return (cells per side, RMS error, measured amplitude, exact amplitude) of the last checkpoint of one run.

    If the twin run `<work>-neg` (amplitude -A) exists, the measured field is the odd part `(f(+A) - f(-A)) / 2`: the
    even nonlinear terms cancel, so the residue is O(A^3) instead of O(A^2) (an acoustic wave steepens at O(A^2))."""
    _, _, _, coef, _ = linear_solution(read_ini(work / "input.ini"))
    pos, dx = fields(work)
    neg_work = work.parent / f"{work.name}-neg"
    neg = fields(neg_work)[0] if neg_work.is_dir() else None
    sq, area, proj = 0.0, 0.0, 0.0 + 0.0j
    for blk, (s, field, da) in pos.items():
        if neg is not None:
            field = 0.5 * (field - neg[blk][1])
        exact = np.real(coef * np.exp(1j * s))
        sq += da * float(((field - exact) ** 2).sum())
        area += da * field.size
        proj += da * complex((field * np.exp(-1j * s)).sum())
    return round(1.0 / dx), math.sqrt(sq / area), 2.0 * abs(proj) / area, abs(coef)


def oracle(args: argparse.Namespace) -> int:
    """Measure every run, print the errors and orders, assert the order of the finest pair."""
    ini = read_ini(args.work[0] / "input.ini")
    mode, k, _, _, cp = linear_solution(ini)
    ph = ini["physics"]
    mu, kappa = float(ph["viscosity"]), float(ph["conductivity"])
    gamma, t = float(ph["gamma"]), float(ini["time"]["time_max"])
    a0 = float(ini["initial_conditions"]["wave_amplitude"])
    rho0 = float(ini["initial_conditions_region_1"]["r"])
    if mode == "shear" and "resistivity" not in ph:
        print(f"exact decay rate nu k^2 = {mu / rho0 * k * k:.6e}")
    elif mode in ("shear", "magnetic"):
        print(f"nu k^2 = {mu / rho0 * k * k:.6e}, eta k^2 = {float(ph['resistivity']) * k * k:.6e}")
    else:
        alpha = k * k / (2.0 * rho0) * (4.0 / 3.0 * mu + (gamma - 1.0) * kappa / cp)
        print(f"Kirchhoff-Stokes rate alpha = {alpha:.6e}")
    results = sorted(run_error(w) for w in args.work)
    prev = None
    for nn, err, measured, exact in results:
        rate = -math.log(measured / (a0 * (rho0 if mode == "acoustic" else 1.0))) / t
        line = f"N {nn:4d}: RMS error {err:.6e}  amplitude {measured:.10e} (exact {exact:.10e})  rate {rate:.6e}"
        if prev is not None:
            line += f"  order {math.log(prev[1] / err) / math.log(nn / prev[0]):+.2f}"
        print(line)
        prev = (nn, err)
    status = 0
    if args.order_min is not None and len(results) > 1:
        (n0, e0, _, _), (n1, e1, _, _) = results[-2], results[-1]
        p = math.log(e0 / e1) / math.log(n1 / n0)
        status = int(p < args.order_min)
        print(f"finest-pair order {p:+.2f} {'>=' if not status else '<'} {args.order_min}: "
              f"{'PASS' if not status else 'FAIL'}")
    if args.order_max is not None and len(results) > 1:
        (n0, e0, _, _), (n1, e1, _, _) = results[-2], results[-1]
        p = math.log(e0 / e1) / math.log(n1 / n0)
        bad = int(p > args.order_max)
        print(f"finest-pair order {p:+.2f} {'<=' if not bad else '>'} {args.order_max} (negative control): "
              f"{'PASS' if not bad else 'FAIL'}")
        status = max(status, bad)
    return status


def energies(work: Path, which: str) -> tuple[float, float, float, float, float]:
    """Return the volume integrals (internal, kinetic, magnetic, total energy) and the max |div B| (central differences,
    interior cells) of the first or last checkpoint (`which`) of an MHD run."""
    ini = read_ini(work / "input.ini")
    ngc = int(ini["grid"]["ngc"])
    eglm =ini["mhd"]["divergence_control"].strip() == "eglm"
    files = sorted(work.glob("wave-*-proc*.h5"))
    its = sorted({int(f.name.split("-")[-2]) for f in files})
    it = its[0] if which == "first" else its[-1]
    tot = np.zeros(4)
    divb = 0.0
    for path in (f for f in files if int(f.name.split("-")[-2]) == it):
        with h5py.File(path, "r") as h5:
            for blk in sorted({key.rsplit("-", 1)[0] for key in h5}):
                dxyz = h5[f"{blk}-dxdydz"][()][::-1]
                f = {v: h5[f"{blk}-{v}"][()].transpose(2, 1, 0)[:, :, ngc] for v in
                     ("r", "ru", "rv", "rw", "rE", "bx", "by", "bz") + (("psi",) if eglm else ())}
                inner = (slice(ngc, -ngc), slice(ngc, -ngc))
                kin = 0.5 * (f["ru"] ** 2 + f["rv"] ** 2 + f["rw"] ** 2) / f["r"]
                mag = 0.5 * (f["bx"] ** 2 + f["by"] ** 2 + f["bz"] ** 2)
                cle = 0.5 * f["psi"] ** 2 if eglm else 0.0
                vol = dxyz[0] * dxyz[1]
                tot += vol * np.array([float((f["rE"] - kin - mag - cle)[inner].sum()), float(kin[inner].sum()),
                                       float(mag[inner].sum()), float(f["rE"][inner].sum())])
                dbx = (f["bx"][ngc + 1:-ngc + 1, ngc:-ngc] - f["bx"][ngc - 1:-ngc - 1, ngc:-ngc]) / (2.0 * dxyz[0])
                dby = (f["by"][ngc:-ngc, ngc + 1:-ngc + 1] - f["by"][ngc:-ngc, ngc - 1:-ngc - 1]) / (2.0 * dxyz[1])
                divb = max(divb, float(np.abs(dbx + dby).max()))
    return tot[0], tot[1], tot[2], tot[3], divb


def budget(args: argparse.Namespace) -> int:
    """VV-6: the Ohmic energy budget of a resistive MHD run and its div(B) against the ideal twin.

    Total energy is conserved by the flux form whatever the fluxes, so its drift checks only round-off. The physics is
    in the split: the field's energy loss must reappear as heat, `dE_int = -dE_mag - dE_kin`; a missing or wrong-signed
    `eta (J x B)` energy flux would keep E but cool the gas. The resistive flux, in curl form, must not raise div(B):
    `max|div B|` with eta stays at or below the ideal run's (times `--div-factor`). On a periodic uniform grid the
    sine wave is discretely divergence-free, so both stay at round-off: the check shows the curl form creates no
    divergence there, not how it behaves against a divergence the grid generates (2:1 seams: #65 P4)."""
    e0 = energies(args.work, "first")
    e1 = energies(args.work, "last")
    ideal = energies(args.ideal, "last")
    d_int, d_kin, d_mag, d_tot = (e1[i] - e0[i] for i in range(4))
    heat = d_int / -(d_mag + d_kin)
    drift = abs(d_tot) / abs(e0[3])
    print(f"magnetic energy {e0[2]:.10e} -> {e1[2]:.10e} (lost {-d_mag:.6e}); kinetic change {d_kin:.3e}")
    print(f"internal energy gained {d_int:.6e}: heat / (field + kinetic loss) = {heat:.9f}")
    print(f"total energy drift {d_tot:.3e} = {drift:.3e} of the total energy")
    print(f"max|div B|: resistive {e1[4]:.6e}, ideal {ideal[4]:.6e}")
    ok = [abs(heat - 1.0) <= args.heat_tol, drift <= args.drift_tol, e1[4] <= args.div_factor * ideal[4] + 1e-14]
    for label, good in zip(("Ohmic heating = field energy loss", "total energy conserved", "div(B) not raised"), ok,
                           strict=True):
        print(f"{label}: {'PASS' if good else 'FAIL'}")
    return int(not all(ok))


def history(work: Path) -> tuple[list[str], np.ndarray]:
    """Return the names (`int_r` -> `r`) and the rows (it, time, integrals...) of the conservation history of a run."""
    lines = next(work.glob("*-conservation_history.dat")).read_text().splitlines()
    names = [v.strip('"').removeprefix("int_") for v in lines[0].split("=", 1)[1].split()][2:]
    rows = np.array([[float(v) for v in line.split()] for line in lines[1:] if line.split()])
    return names, rows


def abs_integrals(work: Path, names: list[str]) -> dict[str, float]:
    """Return the volume integral of |q| of each conserved variable over the interior cells of the last checkpoint:
    the scale at which the round-off of the conserved sum lives (the integral of a sine wave's momentum is zero, so
    its own initial value is no scale)."""
    ngc = int(read_ini(work / "input.ini")["grid"]["ngc"])
    files = sorted(work.glob("wave-*-proc*.h5"))
    last = max(int(f.name.split("-")[-2]) for f in files)
    out = dict.fromkeys(names, 0.0)
    for path in (f for f in files if int(f.name.split("-")[-2]) == last):
        with h5py.File(path, "r") as h5:
            for blk in sorted({key.rsplit("-", 1)[0] for key in h5}):
                vol = float(np.prod(h5[f"{blk}-dxdydz"][()]))
                for v in names:
                    q = h5[f"{blk}-{v}"][()][ngc:-ngc, ngc:-ngc, ngc:-ngc]
                    out[v] += vol * float(np.abs(q).sum())
    return out


def drifts(work: Path) -> dict[str, float]:
    """Return the signed final drift I(T) - I(0) of each conserved integral of a run over its scale (abs_integrals);
    a variable identically zero takes the largest scale of the run. psi, sourced only by the discrete div(B), has no
    scale of its own: its drift is measured against c_h int|B| (psi ~ c_h B, the GLM flux pair)."""
    names, rows = history(work)
    scale = abs_integrals(work, names)
    if "psi" in scale:
        ch = float(read_ini(work / "input.ini")["mhd"]["glm_ch"])
        scale["psi"] = ch * max(scale["bx"], scale["by"], scale["bz"])
    top = max(scale.values())
    return {v: float(rows[-1, 2 + i] - rows[0, 2 + i]) / (scale[v] if scale[v] > 0.0 else top)
            for i, v in enumerate(names)}


MANIFEST = """; FLUME forest (issue #65, P4, VV-7): generated by verification/viscous/waves.py split, do not edit.
[forest]
realms_number = 2

[realm.1]
ini = {name}-r1.ini

[realm.2]
ini = {name}-r2.ini

[forest.topology]
inter_realm_faces_number = 1

[forest.topology.face_1]
realm_a          = 1
face_a           = +x
realm_b          = 2
face_b           = -x
coupling         = {coupling}
coupling_cadence = stage_coincident
"""


def split(args: argparse.Namespace) -> int:
    """Split a single-realm input along x at 0.5 into two realms whose union is its cell set (the MV-14 pattern):

    - mirror: each realm keeps the 4 x 4 blocks of the quadtree on its half, with half the cells along x;
    - refined: the single input refines x > 0.5 by one level (`--refine 0.5 0 1 1`); realm 1 keeps the base level,
      realm 2 takes the refined one on its own (one more uniform level, half the cells per block along x), and the
      seam is the 2:1 face of the single run, glued `coupling = refined` (issue #52).

    The x boundaries must not be periodic: a forest seam cannot close the periodic wrap (`mirror` needs coincident
    cell centres, `periodic` coupling is reserved)."""
    for r in (1, 2):
        ini = configparser.ConfigParser(inline_comment_prefixes=(";",), interpolation=None)
        ini.optionxform = str
        ini.read(args.single)
        if ini["bc_x_min"]["type"] == "periodic":
            sys.exit("waves.py split: the single input is periodic in x (make it with --bc-x extrapolation)")
        ni = int(ini["grid"]["ni"])
        if ni % 2:
            sys.exit(f"waves.py split: ni = {ni} is odd, the realms cannot halve it")
        ini["grid"].update({"ni": str(ni // 2), "emax_x" if r == 1 else "emin_x": "0.5"})
        if args.refined:
            box = [float(ini["amr_marker_1"][k]) for k in ("box_xmin", "box_ymin", "box_xmax", "box_ymax")]
            if box[0] != 0.5 or box[1] > 0.0 or box[2] < 1.0 or box[3] < 1.0:
                sys.exit("waves.py split --refined: the single input must refine exactly x > 0.5 (--refine 0.5 0 1 1)")
            level = int(ini["amr"]["max_level"])
            ini["amr"].update({"markers_number": "0",
                               "iu_ref_levels": str(level if r == 2 else level - 1), "max_level": str(level)})
            ini.remove_section("amr_marker_1")
            ini["initial_conditions"]["amr_iterations"] = "0"
        ini["IO"].update({"output_basename": f"{args.name}-r{r}", "restart_basename": f"{args.name}-r{r}-restart"})
        with (args.out / f"{args.name}-r{r}.ini").open("w") as out:
            ini.write(out)
    (args.out / f"{args.name}.ini").write_text(MANIFEST.format(name=args.name,
                                                               coupling="refined" if args.refined else "mirror"))
    return 0


def conserve(args: argparse.Namespace) -> int:
    """VV-7: the conserved integrals of a run across 2:1 seams, with the negative controls."""
    ok = True
    on = drifts(args.work)
    worst = max(abs(d) for d in on.values())
    print("reflux on : " + "  ".join(f"{v} {d:+.2e}" for v, d in on.items()))
    print(f"   largest |drift| / int|q| {worst:.2e} <= {args.max_drift:.1e}: {'PASS' if worst <= args.max_drift else 'FAIL'}")
    ok &= worst <= args.max_drift
    if args.leaky is not None:
        off = drifts(args.leaky)
        leak = max(abs(d) for d in off.values())
        print("reflux off: " + "  ".join(f"{v} {d:+.2e}" for v, d in off.items()))
        print(f"   largest |drift| / int|q| {leak:.2e} >= {args.min_drift:.1e} (the seams are exercised): "
              f"{'PASS' if leak >= args.min_drift else 'FAIL'}")
        ok &= leak >= args.min_drift
        if args.ideal is not None:
            ideal = drifts(args.ideal)
            diff = max(abs(off[v] - ideal[v]) for v in off)
            print("ideal off : " + "  ".join(f"{v} {d:+.2e}" for v, d in ideal.items()))
            print(f"   dissipative minus ideal leak {diff:.2e} >= {args.min_drift:.1e} (the dissipative fluxes cross "
                  f"the seams unmatched): {'PASS' if diff >= args.min_drift else 'FAIL'}")
            ok &= diff >= args.min_drift
    return 0 if ok else 1


def run_input(work: Path) -> Path:
    """Return the input of a run: input.ini, or the first realm's input of a forest (`<name>-r1.ini`)."""
    return work / "input.ini" if (work / "input.ini").exists() else next(iter(sorted(work.glob("*-r1.ini"))))


def last_state(work: Path) -> dict[tuple, dict[str, np.ndarray]]:
    """Return the interior state of every block of the last checkpoint of a run (every realm of a forest), keyed by the
    block origin (rank-independent)."""
    ngc = int(read_ini(run_input(work))["grid"]["ngc"])
    files = [f for f in sorted(work.glob("*-proc*.h5")) if "restart" not in f.name]
    last = max(int(f.name.split("-")[-2]) for f in files)
    out: dict[tuple, dict[str, np.ndarray]] = {}
    for path in (f for f in files if int(f.name.split("-")[-2]) == last):
        with h5py.File(path, "r") as h5:
            for blk in sorted({key.rsplit("-", 1)[0] for key in h5 if key.endswith("-origin")}):
                key = tuple(np.round(h5[f"{blk}-origin"][()], 12))
                out[key] = {v: h5[f"{blk}-{v}"][()][ngc:-ngc, ngc:-ngc, ngc:-ngc] for v in
                            ("r", "ru", "rv", "rw", "rE", "bx", "by", "bz", "psi") if f"{blk}-{v}" in h5}
    return out


def agree(args: argparse.Namespace) -> int:
    """P5: one run on two backends (or builds), cell by cell on the last checkpoint. Each difference is divided by the
    physical scale of its variable, not by its own maximum: density and energy by their maximum, the momentum by
    rho0 a0 (a wave at rest carries momentum far below the round-off of the state: O(A^2) in an Ohmic wave), the
    field by its maximum (it is the signal), psi by c_h max|B|."""
    a, b = last_state(args.a), last_state(args.b)
    if set(a) != set(b):
        print(f"{args.a.name}: the two runs hold different blocks ({len(a)} vs {len(b)})  FAIL")
        return 1
    ini = read_ini(run_input(args.a))
    reg = ini["initial_conditions_region_1"]
    rho0, p0, gamma = float(reg["r"]), float(reg["p"]), float(ini["physics"]["gamma"])
    names = sorted(next(iter(a.values())))
    peak = {v: max(float(np.abs(blk[v]).max()) for blk in a.values()) for v in names}
    bmax = max((peak[v] for v in ("bx", "by", "bz") if v in peak), default=0.0)
    scale = {}
    for v in names:
        if v in ("ru", "rv", "rw"):
            scale[v] = max(peak[v], rho0 * math.sqrt(gamma * p0 / rho0))
        elif v == "psi":
            scale[v] = float(ini["mhd"]["glm_ch"]) * bmax
        else:
            scale[v] = peak[v]
    rel = {v: max(float(np.abs(a[k][v] - b[k][v]).max()) for k in a) / scale[v] if scale[v] > 0.0 else 0.0
           for v in names}
    worst = max(rel, key=rel.get)
    ok = rel[worst] <= args.tol
    print(f"{args.a.name.split('-np', 1)[1].split('-', 1)[1]:32s} {len(a):5d} blocks  max {rel[worst]:.2e} ({worst})  "
          f"{'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


def main() -> int:
    """Dispatch the subcommand."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    pm = sub.add_parser("make", help="write one input")
    pm.add_argument("out")
    pm.add_argument("--mode", choices=["shear", "acoustic", "magnetic"], required=True)
    pm.add_argument("--model", choices=["euler", "mhd-none", "mhd-glm", "mhd-eglm"], default="euler")
    pm.add_argument("--eta", type=float, default=0.0, help="resistivity (MHD)")
    pm.add_argument("--b0", type=float, default=0.0, help="background field along the wave normal (MHD)")
    pm.add_argument("--amplitude", type=float, default=None, help="wave amplitude (default: per mode)")
    pm.add_argument("--n", type=int, required=True, help="cells per side")
    pm.add_argument("--angle", type=float, default=0.0, help="wave normal angle in the x-y plane, degrees")
    pm.add_argument("--order", type=int, choices=[2, 4], default=4)
    pm.add_argument("--mu", type=float, default=0.01)
    pm.add_argument("--kappa", type=float, default=0.0)
    pm.add_argument("--cfl", type=float, default=0.2)
    pm.add_argument("--time", type=float, default=0.5)
    pm.add_argument("--sign", type=int, choices=[1, -1], default=1, help="sign of the amplitude (the -A twin run)")
    pm.add_argument("--refine", type=float, nargs=4, default=None, metavar=("XMIN", "YMIN", "XMAX", "YMAX"),
                    help="refine the blocks whose centroid lies in this box by one 2:1 level (P4)")
    pm.add_argument("--ratio", type=int, choices=[4, 8], default=4, help="tree ratio of --refine: quadtree 4, octree 8")
    pm.add_argument("--reflux", choices=["true", "false"], default="true", help="[numerics] reflux (false: control)")
    pm.add_argument("--bc-x", choices=["periodic", "extrapolation"], default="periodic",
                    help="x boundaries (extrapolation: the input can be split into realms along x, see split)")
    ps = sub.add_parser("split", help="VV-7: split an input along x at 0.5 into a 2-realm forest")
    ps.add_argument("single", type=Path, help="the single-realm input (made with --bc-x extrapolation)")
    ps.add_argument("out", type=Path, help="output directory: <name>.ini (manifest), <name>-r1.ini, <name>-r2.ini")
    ps.add_argument("name")
    ps.add_argument("--refined", action="store_true",
                    help="the single input refines x > 0.5 (--refine 0.5 0 1 1): realm 2 takes that level, glued 2:1")
    pb = sub.add_parser("budget", help="VV-6: Ohmic energy budget and div(B) of a resistive MHD run")
    pb.add_argument("work", type=Path, help="the resistive run (its first and last checkpoints are kept)")
    pb.add_argument("ideal", type=Path, help="the same case with eta = 0")
    pb.add_argument("--heat-tol", type=float, default=1.0e-3)
    pb.add_argument("--drift-tol", type=float, default=1.0e-13)
    pb.add_argument("--div-factor", type=float, default=1.05)
    pc = sub.add_parser("conserve", help="VV-7: conserved integrals across 2:1 seams")
    pc.add_argument("work", type=Path, help="the run with reflux")
    pc.add_argument("--leaky", type=Path, default=None, help="the same run without reflux (negative control)")
    pc.add_argument("--ideal", type=Path, default=None, help="the leaky run without dissipative coefficients")
    pc.add_argument("--max-drift", type=float, default=1.0e-13)
    pc.add_argument("--min-drift", type=float, default=1.0e-10)
    pa = sub.add_parser("agree", help="P5: the same run on two backends, cell by cell")
    pa.add_argument("a", type=Path)
    pa.add_argument("b", type=Path)
    pa.add_argument("--tol", type=float, default=1.0e-10)
    po = sub.add_parser("oracle", help="judge one or more runs")
    po.add_argument("work", type=Path, nargs="+")
    po.add_argument("--order-min", type=float, default=None)
    po.add_argument("--order-max", type=float, default=None, help="upper bound (a negative control's degraded order)")
    args = parser.parse_args()
    return {"make": make, "oracle": oracle, "budget": budget, "conserve": conserve, "split": split, "agree": agree}[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
