[initial_conditions]
type = riemann-problem
regions_number = 2

[initial_conditions_region_1]
r      = 5.1432014
u      = 2.0451067615658363
v      = 0.0
w      = 0.0
p      = 9.0454500
s      = 1
emin_x = 0.0
emin_y = 0.0
emin_z = 0.0
emax_x = 1.0
emax_y = 20.0
emax_z = 20.0

[initial_conditions_region_2]
r      = 1.4
u      = 0.
v      = 0.
w      = 0.
p      = 1.0
s      = 1
emin_x = 1.0
emin_y = 0.0
emin_z = 0.0
emax_x = 20.0
emax_y = 20.0
emax_z = 20.0

[physics]
ns = 1

[physics_specie_1]
; cp       = 1005.2
; cv       = 718.
cp  = 2.5
cv  = 1.78571
mu  = 1.28535e-5
kd  = 4.59053e-5
dha = 0.

[grid]
ni     = 12
nj     = 12
nk     = 12
ngc    = 4
emin_x = 0.0
emin_y = 0.0
emin_z = 0.0
emax_x = 20.0
emax_y = 20.0
emax_z = 20.0

[equation]
save_memory_status = .false.

[time]
restart          = .false.
restart_basename = sphere-shock-restart
restart_save     = 100
time_max         = 6.0
t_max            = -1
n_save           = 200
time_save        = 0.01
nrk              = 3
CFL              = 0.5
output_basename  = sphere-shock
slices_number    = 2

[slice_1]
slice_itype       = trilinear
slice_save        = 25
slice_ni          = 640
slice_nj          = 1
slice_nk          = 1
slice_emin_x      = 0.1
slice_emin_y      = 10.0001
slice_emin_z      = 10.0001
slice_emax_x      = 19.9
slice_emax_y      = 10.0001
slice_emax_z      = 10.0001

[slice_2]
slice_itype       = trilinear
slice_save        = 100
slice_ni          = 320
slice_nj          = 320
slice_nk          = 1
slice_emin_x      = 0.1
slice_emin_y      = 0.1
slice_emin_z      = 10.0001
slice_emax_x      = 19.9
slice_emax_y      = 19.9
slice_emax_z      = 10.0001

[bc_x_min]
type = 2 ; BC_INFLOW
var1 = 5.1432014
var2 = 2.0451067615658363
var3 = 0.0
var4 = 0.0
var5 = 9.0454500

[bc_x_max]
type = 1 ; BC_EXTRAPOLATION

[bc_y_min]
type = 1 ; BC_EXTRAPOLATION

[bc_y_max]
type = 1 ; BC_EXTRAPOLATION

[bc_z_min]
type = 1 ; BC_PERIODIC

[bc_z_max]
type = 1 ; BC_PERIODIC

[amr]
max_level     = 8
iu_ref_levels = 2
i_prune       = 0
j_prune       = 0
k_prune       = 0
l_prune       = -1
frequency     = 50
iters         = 1
n_markers     = 1

[amr_marker_1]
mode         = 2 ; grad
var          = 1
tol          = 0.5
delta_fine   = 0.125
delta_coarse = 0.5

[amr_marker_2]
mode         = 1 ; geom
solid        = 1
delta_fine   = 0.001
delta_coarse = 0.02

[schemes]
euler_scheme     = 2 ; 1=conservative/2=weno
central_order    = 4 ; 2, 4, 6
weno_n_ror       = 4
; weno_schemes     = 3 ; 1=>godunov, 2=>weno3, 3=>weno5, 4=>weno7, 5=>weno5map, 6=>weno5z
weno_schemes_1     = 4
weno_schemes_2     = 3
weno_schemes_3     = 2
weno_schemes_4     = 1
ror_threshold    = 0.900
ror_n_indexes    = 2 ; number of indexes of variable for ror check
;ror_indexes      = 1 2 ; indexes of variables for ror check
ror_indexes_1      = 1 ; indexes of variables for ror check
ror_indexes_2      = 2 ; indexes of variables for ror check
enable_ror_stats = 1 ; 0=disable, 1=enable
reduction_extent = 0 ; stencil extend for order reduction close to solids
reduced_order    = 3 ; reduced order close to solids
visc_scheme      = 2 ; 1=laplacian/2=conservative
visc_order       = 2 ; 2/4/6

[rotating_frame]
active = .false.
center = 2.0 5.4 3.5
omega  = 1.0 1.0 0.0

[solids]
n_solids = 1

[solid_1]
name            = sphere.off
bc_type         = 1 ; BCS_VISCOUS
n_patches       = 0
multiple_bodies = 80
internal        = .false.
compute_forces  = .false.
moment_center   = 1.5 2.3 10.4
compute_moments = .false.
moving          = .false.
motion_type     = 1
motion_vel      = 0. 0. 1.5
motion_center   = 5.0 5.0 12.0
motion_omega    = 1.2 0.4 0.2

[patches_1_1]
name    = grano.off
bc_type = BCS_GRANO
var1    = 2.0
var2    = 3.0

[patches_1_2]
name    = grano.off
bc_type = BCS_VISCOUS

