[adam]
ni           = 200
nj           = 200
nk           = 2
ngc          = 3
emin_x       = 0.0
emin_y       = 0.0
emin_z       = 0.0
emax_x       = 1.0
emax_y       = 1.0
emax_z       = 1.0
; bc_type      = BC_EXTRAPOLATION BC_EXTRAPOLATION BC_EXTRAPOLATION BC_EXTRAPOLATION BC_EXTRAPOLATION BC_EXTRAPOLATION
nodes_number = 50000
max_level    = 7
nv           = 5
nb           = 5

[euler]
time_max          = 0.25
output_basename   = euler-kt07-xy-
n_save            = 5
ns                = 1
CFL               = 0.3
nrk               = 3
null_x            = .false.
null_y            = .false.
null_z            = .false.
weno_stencils     = 3
fields_gpu_number = 10

[initial_conditions]
nic_regions = 4

[initial_conditions_1]
emin_x     = 0.5
emin_y     = 0.5
emin_z     = 0.0
emax_x     = 1.0
emax_y     = 1.0
emax_z     = 1.0
rho        = 1.0
velocity_x = 0.1
velocity_y = 0.1
velocity_z = 0.0
pressure   = 1.0

[initial_conditions_2]
emin_x     = 0.0
emin_y     = 0.5
emin_z     = 0.0
emax_x     = 0.5
emax_y     = 1.0
emax_z     = 1.0
rho        = 0.5197
velocity_x = -0.6259
velocity_y = 0.1
velocity_z = 0.0
pressure   = 0.4

[initial_conditions_3]
emin_x     = 0.0
emin_y     = 0.0
emin_z     = 0.0
emax_x     = 0.5
emax_y     = 0.5
emax_z     = 1.0
rho        = 0.8
velocity_x = 0.1
velocity_y = 0.1
velocity_z = 0.0
pressure   = 0.4

[initial_conditions_4]
emin_x     = 0.5
emin_y     = 0.0
emin_z     = 0.0
emax_x     = 1.0
emax_y     = 0.5
emax_z     = 1.0
rho        = 0.5197
velocity_x = 0.1
velocity_y = -0.6259
velocity_z = 0.0
pressure   = 0.4
